### PR TITLE
widget: Stretch controlArea to buttonsArea

### PR DESCRIPTION
**Pull request by irgolic**
##### Issue
Fixes https://github.com/biolab/orange3/issues/5225

##### Description of changes
You're right @markotoplak, this works well for all widgets :D
Although, some more testing would be nice. Combine this PR with https://github.com/biolab/orange3/pull/5013

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by markotoplak** [comment]
Originally this PR did not work for me. I tried to fix it: I think we need to set stretch only after we add the object. :)

But I am not sure this works that well with widgets with no expanding elements. Here is a scatterplot, when space is constrained:

image

And if I expand it, is starts looking a bit strange:

image

What do you think?

**Comment by irgolic** [comment]
You're right, the old version doesn't work for me either. Not sure how I messed up that commit, thanks for the fix.

But you're right, it doesn't look good with the stretch upon expanding the window. What if I make this into an obscure GUI layout option and discourage it in general?

**Comment by markotoplak** [comment]
Oh, the above screenshots were done on biolab/orange3#5013.

I if do them on master, I get normal behavior (see below). So this PR is OK, I think, just biolab/orange3#5013 branch will have to be fixed by adding a rubber, as there was in the master, after controls in widgets.

image

**Comment by markotoplak** [comment]
We talked about this with @irgolic. He is going to solve the problem differently.

**Comment by irgolic** [comment]
I think with this commit, we're good.

**Pull request merged**
